import SessionProviders from "@/Providers/SessionProviders";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Credit from "@/components/Credit";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <SessionProviders>
          <Toaster />
          {children}
          <Credit />
        </SessionProviders>
      </body>
    </html>
  );
}
